
# Setup
title: Exploratorio Humanidades Digitales
tagline: Humanidades Digitales desde la Universidad de Antioquia
description: 'cool kids never have the time'
url: "https://neotropico.github.io/"
baseurl: "/ExploratorioHD/"

plugins:
jekyll-relative-links

relative-links:
enable: true
collections: false

author:
  name:           Equipo del Exploratorio
  url:            

paginate:         4

